aliases:
  SP500: "^GSPC"
  DAX: "^GDAXI"
  IBEX_35: "^IBEX"
  CSUSHPISA: "USA_HPI_REAL"
  MORTGAGE30US: "Mortgage_rate_USA"
  MIR.M.FR.B.A2C.A.R.A.2250.EUR.N: "Mortgage_rate_FRA"
  MIR.M.IT.B.A2C.A.R.A.2250.EUR.N: "Mortgage_rate_ITA"
  MIR.M.DE.B.A2C.A.R.A.2250.EUR.N: "Mortgage_rate_DEU"
  MIR.M.ES.B.A2C.A.R.A.2250.EUR.N: "Mortgage_rate_ESP"
  BTP_Bund_Spread: "Sovereign_spread_vs_Germany_ITA"
  Bonos_Bund_Spread: "Sovereign_spread_vs_Germany_ESP"
  OAT_Bund_Spread: "Sovereign_spread_vs_Germany_FRA"
  Treasury_Bund_Spread: "Sovereign_spread_vs_Germany_USA"
  DEXUSEU: "EUR_USD"
  DEXJPUS: "USD_JPY"
  DEXUSUK: "GBP_USD"
  DEXCHUS: "USD_CNY"
  "TTF_GAS / PNGASEUUSDM": "TTF_GAS"
